# Generated by Django 2.2.1 on 2019-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_division', models.IntegerField(choices=[(2, '추돌 사고'), (3, '전복 사고'), (1, '낙석'), (4, '야생 동물')])),
                ('area_division', models.IntegerField(choices=[(1, '서울/경기'), (3, '충청도'), (5, '강원도'), (6, '경상남도'), (2, '전라도'), (4, '경상북도')])),
                ('video', models.FileField(null=True, upload_to='static/video/')),
            ],
        ),
    ]
