# Generated by Django 2.2.1 on 2019-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anomaly_division',
            field=models.IntegerField(choices=[(2, '추돌 사고'), (4, '야생 동물'), (3, '전복 사고'), (1, '낙석')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='area_division',
            field=models.IntegerField(choices=[(1, '서울/경기'), (5, '강원도'), (2, '전라도'), (3, '충청도'), (4, '경상북도'), (6, '경상남도')]),
        ),
    ]
